In [43]:
import pandas as pd
df = pd.read_excel("data_for_bootstrap.xlsx")
df.head()

Date  Crude oil, Brent  Crude oil, Dubai
0  2015M02             57.93             55.83
1  2015M03             55.79             54.91
2  2015M04             59.39             58.80
3  2015M05             64.56             63.69
4  2015M06             62.34             61.78

### две связанные выборки: цены на нефть Brent и Dubai с 2015 по 2023 год (100 наблюдений) => используем бутстреп для связанных выборок (хотим понять, насколько сильно цены на нефть разных марок коррелируют между собой)


In [44]:
import numpy as np

In [45]:
!pip install arch

In [46]:
from arch.bootstrap import IIDBootstrap, IndependentSamplesBootstrap

In [47]:
rng = np.random.default_rng(111111)

In [48]:
x = np.array(df['Crude oil, Brent'])
x

array([ 57.93,  55.79,  59.39,  64.56,  62.34,  55.87,  46.99,  47.24,
        48.12,  44.42,  37.72,  30.8 ,  33.2 ,  39.07,  42.25,  47.13,
        48.48,  45.07,  46.14,  46.19,  49.73,  46.44,  54.07,  54.89,
        55.49,  51.97,  52.98,  50.87,  46.89,  48.69,  51.37,  55.16,
        57.62,  62.57,  64.21,  68.99,  65.42,  66.45,  71.63,  76.65,
        75.19,  74.44,  73.13,  78.86,  80.47,  65.17,  56.46,  59.27,
        64.13,  66.41,  71.2 ,  70.53,  63.3 ,  64.  ,  59.25,  62.33,
        59.37,  62.74,  65.85,  63.6 ,  55.  ,  32.98,  23.34,  31.02,
        39.93,  42.81,  44.26,  41.09,  40.47,  43.23,  49.87,  54.55,
        61.96,  65.19,  64.77,  68.04,  73.07,  74.39,  70.02,  74.6 ,
        83.65,  80.77,  74.31,  85.53,  95.76, 115.59, 105.78, 112.37,
       120.08, 108.92,  98.6 ,  90.16,  93.13,  91.07,  80.9 ,  83.09,
        82.71,  78.53,  84.11,  75.7 ])

In [49]:
y = np.array(df['Crude oil, Dubai'])
y

array([ 55.83,  54.91,  58.8 ,  63.69,  61.78,  56.25,  47.22,  46.15,
        46.55,  42.22,  34.77,  27.  ,  29.5 ,  35.18,  39.04,  43.95,
        45.83,  42.62,  43.74,  43.74,  48.26,  43.77,  51.78,  53.37,
        54.17,  51.16,  52.45,  50.31,  46.44,  47.63,  50.43,  53.86,
        55.58,  60.58,  61.41,  66.02,  62.79,  63.29,  68.43,  73.66,
        73.22,  72.72,  72.13,  77.02,  78.96,  65.11,  56.47,  58.96,
        64.32,  66.8 ,  70.66,  69.13,  61.3 ,  62.91,  58.92,  60.84,
        58.47,  61.41,  64.41,  63.76,  54.51,  33.75,  23.27,  31.56,
        40.14,  42.64,  43.71,  41.1 ,  39.7 ,  42.58,  49.26,  54.16,
        60.37,  63.95,  62.37,  65.98,  70.96,  73.  ,  68.85,  72.24,
        81.22,  79.8 ,  72.76,  83.11,  93.13, 113.11, 102.68, 108.32,
       115.73, 106.48,  97.75,  90.63,  90.59,  86.28,  76.78,  80.03,
        81.21,  77.52,  83.83,  75.08])

In [50]:
obs_id = rng.choice(range(100), size=100)
obs_id

array([76, 34, 55, 66, 42, 89, 22, 55,  1, 40, 69, 28, 22, 85, 62, 68, 47,
        6, 84, 98, 46, 89, 28, 95, 95, 25, 61, 15, 74,  2, 93, 15, 10, 31,
       16, 35, 58, 47, 16, 86, 64, 79, 79, 30, 23, 23, 47, 69, 13, 27,  2,
       59, 46, 87, 50, 38,  4,  9, 14, 79, 61, 13, 78, 25, 71, 96, 61, 78,
       72, 97, 65, 45, 58, 10, 39, 47, 91, 40,  9, 67, 23, 75, 13, 67, 29,
       30, 35, 22,  3, 78, 62, 76, 12, 53, 95, 79, 80, 19, 46, 80])

In [51]:
x_star1 = x[obs_id]
x_star1

array([ 73.07,  64.21,  62.33,  44.26,  73.13, 108.92,  54.07,  62.33,
        55.79,  75.19,  43.23,  46.89,  54.07, 115.59,  23.34,  40.47,
        59.27,  46.99,  95.76,  84.11,  56.46, 108.92,  46.89,  83.09,
        83.09,  51.97,  32.98,  47.13,  64.77,  59.39,  91.07,  47.13,
        37.72,  55.16,  48.48,  68.99,  65.85,  59.27,  48.48, 105.78,
        39.93,  74.6 ,  74.6 ,  51.37,  54.89,  54.89,  59.27,  43.23,
        39.07,  50.87,  59.39,  63.6 ,  56.46, 112.37,  71.2 ,  71.63,
        62.34,  44.42,  42.25,  74.6 ,  32.98,  39.07,  70.02,  51.97,
        54.55,  82.71,  32.98,  70.02,  61.96,  78.53,  42.81,  65.17,
        65.85,  37.72,  76.65,  59.27,  90.16,  75.19,  44.42,  41.09,
        54.89,  68.04,  39.07,  41.09,  48.69,  51.37,  68.99,  54.07,
        64.56,  70.02,  23.34,  73.07,  33.2 ,  64.  ,  83.09,  74.6 ,
        83.65,  46.19,  56.46,  83.65])

In [52]:
y_star1 = y[obs_id]
y_star1

array([ 70.96,  61.41,  60.84,  43.71,  72.13, 106.48,  51.78,  60.84,
        54.91,  73.22,  42.58,  46.44,  51.78, 113.11,  23.27,  39.7 ,
        58.96,  47.22,  93.13,  83.83,  56.47, 106.48,  46.44,  80.03,
        80.03,  51.16,  33.75,  43.95,  62.37,  58.8 ,  86.28,  43.95,
        34.77,  53.86,  45.83,  66.02,  64.41,  58.96,  45.83, 102.68,
        40.14,  72.24,  72.24,  50.43,  53.37,  53.37,  58.96,  42.58,
        35.18,  50.31,  58.8 ,  63.76,  56.47, 108.32,  70.66,  68.43,
        61.78,  42.22,  39.04,  72.24,  33.75,  35.18,  68.85,  51.16,
        54.16,  81.21,  33.75,  68.85,  60.37,  77.52,  42.64,  65.11,
        64.41,  34.77,  73.66,  58.96,  90.63,  73.22,  42.22,  41.1 ,
        53.37,  65.98,  35.18,  41.1 ,  47.63,  50.43,  66.02,  51.78,
        63.69,  68.85,  23.27,  70.96,  29.5 ,  62.91,  80.03,  72.24,
        81.22,  43.74,  56.47,  81.22])

In [53]:
def corr(x, y):
    corr_matrix = np.corrcoef(x, y)
    return corr_matrix[0,1]

In [54]:
corr(x_star1, y_star1)
# посчитали первый шаг бутстрепа вручную

0.9979852664214496

In [55]:
boot_xy = IIDBootstrap(x, y, seed=111111)
boot_xy.conf_int(corr, method='basic', reps=10000, size=0.95)
#с помощью бутстрепа получили интервал для корреляции марок Brent и Dubai

array([[0.9974835],
       [0.9988406]])

### Вывод: как и следовало ожидать, цены на нефть разных марок имеют сильную положительную линейную взаимосвязь, т.е. у марок Brent и Dubai будет одинаковая реакция на мировое изменение уровня цен.